version: '3.8'

services:
  project_backend:
    build:
      context: ./project_backend
    container_name: django-project-backend
    env_file: .env
    volumes:
      - ./project_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  project_frotend:
    build:
      context: ./project_frotend
    container_name: react-project_frotend
    volumes:
      - ./project_frotend:/app
    ports:
      - "3000:3000"

  db:
    image: postgres:13
    container_name: postgres-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx-server
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - project_frotend
      - project_backend

volumes:
  postgres_data:
