version: '3.8'

services:
  backend:
    build:
      context: ./project_backend
      dockerfile: Dockerfile
    container_name: django-backend-prod
    volumes:
      - ./project_backend:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file: .env.prod
    depends_on:
      - postgres
    command: >
      gunicorn --chdir /app/project_backend
      --workers 3
      --bind 0.0.0.0:8000
      project_backend.wsgi:application
    environment:
      - DJANGO_SETTINGS_MODULE=project_backend.settings
      - PYTHONUNBUFFERED=1
      - DJANGO_ENV_FILE=.env.prod
  

  postgres:
    image: postgres:15
    pull_policy: if_not_present
    container_name: postgres-db-prod
    restart: always
    ports:
      - "5432:5432"
    env_file: .env.prod  # Load environment variables from .env.prod
    volumes:
      - postgres-db-prod:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  nginx:
    image: nginx
    pull_policy: if_not_present
    container_name: nginx-prod
    ports:
      - "8443:8443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/keys:/etc/letsencrypt/keys:ro
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal:ro
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - backend

volumes:
  postgres-db-prod:
    name: solar_project_postgres_data
